dbt_ecomm:
  outputs:
    dev:
      dbname: E-Commerce
      host: postgres
      pass: your_database_password
      port: 5432
      schema: dev_schema
      threads: 4
      type: postgres
      user: your_database_user
  target: dev
